# Generated by Django 3.0.3 on 2021-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancel_event',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
