# Generated by Django 3.0.3 on 2021-05-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_count2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Meet_link',
            field=models.URLField(blank=True, default='NONE'),
        ),
    ]
